# Generated by Django 3.2.6 on 2021-09-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='scrapperprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilelink', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scrapped_status', models.BooleanField(default=True)),
                ('Interest', models.TextField(blank=True, null=True)),
                ('Accomplishments', models.TextField(blank=True, null=True)),
                ('Skills', models.TextField(blank=True, null=True)),
                ('Education', models.TextField(blank=True, null=True)),
                ('Experience', models.TextField(blank=True, null=True)),
                ('Contact', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
