# Generated by Django 3.2.6 on 2021-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapperprofile',
            name='profilelink',
            field=models.CharField(max_length=200),
        ),
    ]
