# Generated by Django 3.2.6 on 2021-09-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_scrapperprofile_profilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperprofile',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
