# Generated by Django 3.2.6 on 2021-09-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_scrapperprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapperprofile',
            name='Accomplishments',
        ),
        migrations.RemoveField(
            model_name='scrapperprofile',
            name='Experience',
        ),
        migrations.AddField(
            model_name='scrapperprofile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
