# Generated by Django 3.2.6 on 2021-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210920_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapperprofile',
            name='profilelink',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
